def eind():
        print("")
        print("je bent net klaar met het verhaal en hebt gewonnen of verloren.")
        print("je word nu de keuzen gegeven als je opnieuw wil spelen om een ander verhaal te prober")
        print("")
        print("als je op nieuw wil spellen kies uit")
        print("")
        print("a. ja")
        print("b. stop")
        print()
        print("kies uit a of b")
        kan = input() 
        if kan=="a":
                return_begin()
        if kan=="b":
                print("dit is het eind.")
                print("ik hoop dat je genoten heb van deze reis ik hoop dat je nog eens mee doe")
                print("")
def vraag_5_4a():
        print()
        print("vraag 5. je hebt de keuzen om nu naar Nederland te gaan en te winnen of om op te geven.")
        print("kies nu")
        print("")
        print("a. ga naar Nederland kost 15 dagen")
        print("b. geef op")
        print("")
        print("kies uit a of b")
        goed = input() 
        if goed=="a":
                print("")
                print("je bent veilig aanngekomen in Nederland en hebt het spell gewonnen.")
                print("je kan van af nu af aan kan je vrij reizen tussen de landen in de EU.")
                print("")
                print("tijd over 19 dagen")
                eind()
        if goed=="b":
                print("je wat is dit nu met youw met deze keuzen.")
                print("je had alleen naar Nederland moeten gaan en je had gewonnen waarom gaf je op?")
                print("zoek het toch uit je ben de gene met de schulden en zonder werk ik niet.")
                print("ik hoop dat je blei ben met je keuzen")
                eind()
def vraag_4_3b2():
        print()
        print("vraag 4. je hebt de keuzen om nu naar Nederland te gaan en te winnen of om op te geven.")
        print("kies nu")
        print("")
        print("a. ga naar Nederland kost 20 dagen")
        print("b. geef op")
        print("")
        print("kies uit a of b")
        goed = input() 
        if goed=="a":
                print("")
                print("je bent veilig aanngekomen in Nederland en hebt het spell gewonnen.")
                print("je kan van af nu af aan kan je vrij reizen tussen de landen in de EU.")
                print("")
                print("tijd over 10 dagen")
                eind()
        if goed=="b":
                print("je wat is dit nu met youw met deze keuzen.")
                print("je had alleen naar Nederland moeten gaan en je had gewonnen waarom gaf je op?")
                print("zoek het toch uit je ben de gene met de schulden en zonder werk ik niet.")
                print("ik hoop dat je blei ben met je keuzen")
                eind()
def vraag_4_3b1():
        print("je hebt nu de keuzen om te blijven of om te gaan kies uit")
        print()
        print("vraag 4. oke de politie vraagt wat ik aan het doen was waneer de moord was gepleegt.")
        print("hiervoor moet je uitvogelen wat ik het liefst doe.")
        print("veel succes")
        print("")
        print("a. lijf in Belgie kost 1 dag legaal")
        print("b. Nederland kost 15 dagen legaal")
        print()
        print("kies uit a of b")
        kan = input() 
        if kan=="a":
                print("je bleef in Belgie voor nog 1 dag.") 
                print("je hebt nog 49 dagen")
                print("")
                vraag_5_4a()
        if kan=="b":
                print("je bent veilig aanngekomen in Nederland en hebt het spell gewonnen.")
                print("je kan van af nu af aan kan je vrij reizen tussen de landen in de EU.")
                print("")
                print("tijd over 20 dagen")
                print("")
                eind()
def vraag_3_2c():
        print("vraag 3. je bent nu in Denemark.")
        print("je moet nu kiezen maar denk na er is een storm op zee. kies uit")
        print("")
        print("a. nederland kost je 30 dagen legaal")
        print("b. england kost je 20 dagen ilegaal")
        print("c. duitsland kost 20 dagen legaal")
        print()
        print("kies uit a.b of c")
        vul = input() 
        if vul=="a":
                print("je bent dood gegaan door een storm op zee vanwegen de haast die je had om te winnen.")
                print("")
                print("je hebt verloren")
                eind()
        if vul=="b":
                print("je komt veilig aan bij england maar word wel aangehouden.")
                print("het kost 51 dagen je hebt nog 45 dagen over")
                vraag_4_3b2()
        if vul == ("c"):
                print("je kwam om door een storm op zee vanwegen de haast die je om te winnen ")
                print("")
                print("je hebt verloren")
                eind()
        print()
        print()
def vraag_3_2b():
        print("")
        print("vraag 3. je bent bijna over de grens van Nederland.")
        print("je hoef allen nog maar te kiezen hoe je gaat kies uit.")
        print("")
        print("a. Nederland kost je 30 dagen ilegaal")
        print("b. Belgie kost 20 dagen legaal")
        print("")
        print("kies uit a of b")
        goed = input() 
        if goed=="a":
                print("")
                print("je bent veilig aanngekomen in Nederland en hebt het spell gewonnen.")
                print("je kan van af nu af aan kan je vrij reizen tussen de landen in de EU.")
                print("")
                print("tijd over 49 dagen.")
                print("")
                eind()
        if goed=="b":
                print("je komt veilig aan in Belgie.")
                print("je hebt nog maar 50 dagen over")
                print("")
                vraag_4_3b1()
def vraag_2_1b():
        print()
        print("vanwegen dat je nu maar alleen 1 kant op kan gaan krijg je 1 extra keuzen bij.")
        print("")
        print("a. Russia kost 6 dagen ilegaal")
        print("b. geef op kost je niets")
        print()
        print("kies uit a of b")
        kan = input() 
        if kan=="a":
                print("omdat je geen paspoort had werd je neer geschoten, voor identieteit vroud .")
                print("je bent dood")
                print("je hebt verloren")
                eind()
        if kan=="b":
                print("omdat je nu op geef heb je geen consequences van de geen verlies en kan je weer normaal leven.")
                eind()
def vraag_2_1a():
        print("vraag 2. omdat je deze keuzen heb gemaakt ga je nu op een ander eind.")
        print("je gaat nu kiezen, kies uit.")
        print("")
        print("a. zweden kost je 40 dagen je gaat legaal")
        print("b. duitsland kost je 55 dagen maar gaat ilegaal")
        print("c. denemarkt kost je 50 dagen je gaat legaal")
        print()
        print("kies uit a.b of c")
        vul = input() 
        if vul=="a":
                print("je bent dood gegaan door een storm op zee vanwegen, de haast die je had om de geld te winnen.")
                print("je hebt nu verloren.")
                eind()
        if vul=="b":
                print("je komt net aan in duitsland.")
                print("het koste je 15  dagen extra omdat je werdd aan gehouden voor het ilegaal reizen.") 
                print("je hebt nog maar 85 dagen over en moet nog maar 1 grens over.")
                vraag_3_2b()
        if vul == ("c"):
                print("je komt veilig aan in denemark.") 
                print("je hebt 65 dagen verloren en heb nog 96 dagen.")
                vraag_3_2c()
                print()
                print()
def return_1(): 
        print("denk goed na hoe je gaat reizen want vanaf nu ieder keuzen die je maak heb in vloed op de eind.")
        print("je moet nu kiezen uit.")
        print("")
        print("a. Russia kost 6 dagen plus legaal")
        print("b. Mongolia kost 4 dagen plus legaal")
        print("c.Niets doen kost niets")
        print()
        print("kies uit a.b of c")
        antwoord = input() 
        if antwoord=="a":
                        print("je komt daar het remensen zien je daar en denken dat je daar ben voor oorlog en word gearesteerd.")
                        print("is wel een betje eng he")
                        print("verliest 21 dagenheb nog maar 161 dagen")
                        vraag_2_1a()
        if antwoord=="b":
                        print("je komt daar net aan had geen problemen met reizen.")
                        print(" het kost je alleen 19 dagen en je heb nu nog maar 163 dagen over ")
                        vraag_2_1b()
        if antwoord=="c":
                        print("omdat je niets doet heb je opgegeven op de prijs en ben je niet verplicht iets te doen.")
                        print("wat ben je toch een idiote. ")
                        eind()
def return_begin():
        print ("Hello You! wie ben jij?")
        print ("ik ben de Chatbot en ik heet Mikel!")
        username = input("Hoe heet jij? ")
        print("")
        print("Hallo " + username)
        print("")
        print("ik ben (g). ik werk bij een spell bedrijf.")
        print("jij heb de opsie om aan een spell mee te doen en 1 biljoen euro winnen.")
        print("om te winnen moet je binnen 182 dagen in nederland komen.")
        print("")
        print("hier onder staan de regels")
        print("")
        print("regel 1 je kan alleen reizen via land en water")
        print("regel 2 als je gearesteerd word voor ilegaal reizen dat kost je 15 dagen extra")
        print("regel 3 om een grens door tegaan moet je apart een extra faste koste betallen 15 dagen en ilegaal 6 ")
        print("word je gearesteerd als je ilegaal reis dan betaal je 15 dagen extra dagen er bij")
        print("")
        print("tips")
        print("tip 1. kijk op de wereld map om de reis bij te houden. ")
        print("tip 2. het kost je ook dagen om een grens over te gaan. der dichter bij de land der duurder het word")
        print("tip 3. als je op land of op water reist word bepaald via een wereld map dus kijk mee hoe je reis")
        print("tip 4. het verhaal speelt zich af in de jaar 2022")
        print("")
        print("let goed op. als je een vraag antwoord woord je na een ander eind geleden dus denk goed na voor je vraag")
        print("")
        print("oke,")
        print("schrijf -start- als je wil beginen")
        print("in input")
        oke = input()
        if oke=="start":
                return_1()
return_begin()